type Stock {
    _id: ID
    quantity: Int!
    price: String!
    item: Item!
    location: Location!
}

type Item {
    _id: ID
    upc: String!
    title: String!
    brand: String!
}

type User {
    _id: ID
    username: String!
    password: String!
    email: String!
    locations: [Location!]!
}

type Location {
    _id: ID
    title: String!
    salesTax: Int
    users: [User!]!
    inventory: [Stock!]!
}

input LocationInput {
    title: String!
}

input JoinLocationInput {
    title: String!
}

input ItemInput {
    upc: String!
    title: String!
    brand: String!
}

type ProductSuggestions {
    titleSuggestions: [String!]
    brandSuggestions: [String!]
    priceSuggestions: [Float!]
}

type Authentication {
    userId: ID!
    token: String!
    tokenExpiration: String!
}

input UserInput {
    username: String!
    email: String!
    password: String!
}

input LoginInput {
    email: String!
    password: String!
}

input StockInput {
    locationId: String!
    upc: String!
    price: String!
    quantity: Int!
}

input UpdateStockInput {
    stockId: String!
    upc: String!
    price: String
    quantity: Int
}

type RootQuery {
    user: User!
    location(id: String!): Location!
    item(upc: String!): Item!
    login(loginInput: LoginInput!) : Authentication!
    productSuggestions(upc: String!) : ProductSuggestions!
}

type RootMutation {
    createUser(userInput: UserInput!) : User!
    createLocation(locationInput: LocationInput!) : Location!
    createItem(itemInput: ItemInput!) : Item!
    createStock(stockInput: StockInput!): Stock!
    updateStock(updateStockInput: UpdateStockInput) : Stock!
    joinLocation(joinLocationInput: JoinLocationInput!) : Location!
}

schema {
    query: RootQuery
    mutation: RootMutation
}